theme:
  name: material
site_name: DeepNone
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
repo_url: https://github.com/jackdreilly/deepnone
